apiVersion: v1
data:
  APP_SECRET: MIGHTYSECRET
  COMPOSE_HTTP_TIMEOUT: "120"
  FRONTEND_URL: http://nginx:80
  PRISMA_ENDPOINT: http:prisma:4466
  PRISMA_ENDPOINT_CONTAINER: http://prisma:4466
  PRISMA_SECRET: LALALALA
  YOGA_ENDPOINT: http://yoga:4000
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-env
  name: app-env
