apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f kompose.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: socket
  name: socket
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    io.kompose.service: socket
status:
  loadBalancer: {}
